apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: redis-config
#          resources:
          # Define resource limits and requests if needed
          # limits:
          #   cpu: "1"
          #   memory: "512Mi"
          # requests:
          #   cpu: "500m"
          #   memory: "256Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    dir /data
